USE [master]
GO

/****** Object:  Database [dbCrk]    Script Date: 17/02/2019 19:25:35 ******/
CREATE DATABASE [dbCrk]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbCrk', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\dbCrk.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbCrk_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\dbCrk_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbCrk] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbCrk].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbCrk] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbCrk] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbCrk] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbCrk] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbCrk] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbCrk] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbCrk] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbCrk] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbCrk] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbCrk] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbCrk] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbCrk] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbCrk] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbCrk] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbCrk] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbCrk] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbCrk] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbCrk] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbCrk] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbCrk] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbCrk] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbCrk] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbCrk] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbCrk] SET  MULTI_USER 
GO

ALTER DATABASE [dbCrk] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbCrk] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbCrk] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbCrk] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbCrk] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbCrk] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbCrk] SET  READ_WRITE 
GO


